### ISSUE TITLE
A User can view a list of their Todo items

### ISSUE THREAD

**Issue by a-nguyen-kangan** [kimchieater/to_do_app_angry_cats#2]
- [x] Select and setup a backend service (preferably a Headless CMS)
- [x] Create the FE
- [ ] Connect to backend service
